[paths]
worship_dir = C:\Users\Public\Documents\Area42\Worship
ccli_dir = C:\Users\pasto\OneDrive - United Parish of Elkton (1)\Music\CCLI
bulletin_dir = C:\Users\pasto\OneDrive - United Parish of Elkton (1)\Documents\Bulletins

elkton_openlp_root = C:\Users\pasto\OneDrive - United Parish of Elkton (1)\Shared with Everyone\OpenLP
lb_openlp_root = C:\Users\pasto\OneDrive - United Parish of Elkton (1)\Shared with Everyone\LBopenLP

; elkton_songs_db = C:\Users\pasto\OneDrive - United Parish of Elkton (1)\Shared with Everyone\OpenLP\songs\songs.sqlite
; lb_songs_db = C:\Users\pasto\OneDrive - United Parish of Elkton (1)\Shared with Everyone\LBopenLP\songs\songs.sqlite

; elkton_bible_db = C:\Users\pasto\OneDrive - United Parish of Elkton (1)\Shared with Everyone\OpenLP\bibles\Good News Translation.sqlite
; lb_bible_db = C:\Users\pasto\OneDrive - United Parish of Elkton (1)\Shared with Everyone\LBopenLP\bibles\New Revised Standard Version.sqlite
